module com.tugalsan.tst.pdf {
//    requires gwt.user;
    requires java.desktop;
    requires boxable;
    requires org.apache.pdfbox;
    requires pdfbox.examples;
    requires com.tugalsan.api.sql.conn;
//    requires org.apache.pdfbox;
//    requires org.bouncycastle.provider;
//    requires org.bouncycastle.pkix;
//    requires org.apache.commons.logging;
//    requires org.bouncycastle.util;
    requires com.tugalsan.api.log;
    requires com.tugalsan.api.function;
    requires com.tugalsan.api.file;
    requires com.tugalsan.api.file.html;
    requires com.tugalsan.api.string;
    requires com.tugalsan.api.charset;
    requires com.tugalsan.api.url;
    requires com.tugalsan.api.unsafe;
    requires com.tugalsan.api.union;
    requires com.tugalsan.api.file.pdf.openpdf;
    requires com.tugalsan.api.file.pdf.pdfbox3;
//    requires com.tugalsan.api.log;
//    requires com.tugalsan.api.function;
//    requires com.tugalsan.api.tuple;
//    requires com.tugalsan.api.input;
//    requires com.tugalsan.api.shape;
//    requires com.tugalsan.api.unsafe;
//    requires com.tugalsan.api.file;
//    requires com.tugalsan.api.file.img;
//    requires com.tugalsan.api.file.pdf.pdfbox3;
//    requires com.tugalsan.api.file.pdf.openpdf;
//    requires com.tugalsan.api.url;
//    requires com.tugalsan.api.union;
//    requires com.tugalsan.lib.file.pdf.sign;
}
